# This file was generated by GoReleaser. DO NOT EDIT.
class Atg < Formula
  desc "Tool to assume the AWS role and go"
  homepage "https://github.com/gocaio/atg"
  version "1.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gocaio/atg/releases/download/v1.5.0/ATG_v1.5.0_darwin_amd64.tar.gz"
    sha256 "c9e0fc1864321716ff64c68e34f35696869c91dfa11091440a717271020a1ee4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gocaio/atg/releases/download/v1.5.0/ATG_v1.5.0_linux_amd64.tar.gz"
      sha256 "d822cd0e69c2e5848099abea7bfb793798ad0fd1fed26b10900a85dda49e720c"
    end
  end

  def install
    bin.install "atg"
  end

  test do
    system "#{bin}/atg", "help"
  end
end
